// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLCb1FnYFFE44ftnQYeyQJSYnp-0Tv11I',
    appId: '1:509773151038:web:935122fc0a767d0a334a6f',
    messagingSenderId: '509773151038',
    projectId: 'fir-practices-79ac1',
    authDomain: 'fir-practices-79ac1.firebaseapp.com',
    storageBucket: 'fir-practices-79ac1.firebasestorage.app',
    measurementId: 'G-0T588HJVN2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-aRlN4ji5N3AJxDdepZBI732yxKKm8Qc',
    appId: '1:509773151038:android:819557bb38dc5fc6334a6f',
    messagingSenderId: '509773151038',
    projectId: 'fir-practices-79ac1',
    storageBucket: 'fir-practices-79ac1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALvg9YJjh31S78z35HBBM7d828qi-OfO8',
    appId: '1:509773151038:ios:9e2f6a2aae4e1e7f334a6f',
    messagingSenderId: '509773151038',
    projectId: 'fir-practices-79ac1',
    storageBucket: 'fir-practices-79ac1.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALvg9YJjh31S78z35HBBM7d828qi-OfO8',
    appId: '1:509773151038:ios:9e2f6a2aae4e1e7f334a6f',
    messagingSenderId: '509773151038',
    projectId: 'fir-practices-79ac1',
    storageBucket: 'fir-practices-79ac1.firebasestorage.app',
    iosBundleId: 'com.example.firebasePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLCb1FnYFFE44ftnQYeyQJSYnp-0Tv11I',
    appId: '1:509773151038:web:b9c5bb682211b2ff334a6f',
    messagingSenderId: '509773151038',
    projectId: 'fir-practices-79ac1',
    authDomain: 'fir-practices-79ac1.firebaseapp.com',
    storageBucket: 'fir-practices-79ac1.firebasestorage.app',
    measurementId: 'G-5XT3Y78KGM',
  );
}
